### ISSUE TITLE
Scaling Issue

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#1046]
The following project will render at 50% scale, even though it should render at 100% scale (because we undo the scaling transformation).

```haxe
package;

import kha.Framebuffer;
import kha.System;

class Main {

    public static function main() {
        System.start({title: "Kha", width: 720, height: 480}, init);
    }

    private static function init(window) {
        System.notifyOnFrames(render);
    }

    public static function render(framebuffers:Array<Framebuffer>):Void {
        var framebuffer = framebuffers[0];

        framebuffer.g2.begin(true);

        var backup = kha.math.FastMatrix3.identity();
        backup.setFrom(framebuffer.g2.transformation);
        framebuffer.g2.scale(0.5, 0.5);
        framebuffer.g2.transformation.setFrom(backup);

        framebuffer.g2.color = kha.Color.Red;
        framebuffer.g2.fillRect(0, 0, 64, 64);
        framebuffer.g2.color = kha.Color.White;

        framebuffer.g2.end();
    }
}
```

**Comment by Joncom** [comment]
It appears that the following khafile setting is needed to reproduce this: `project.targetOptions.html5.webgl = false;`

**Comment by RobDangerous** [comment]
This happens because the canvas backends needs to know when the transformation changed because it can not use the transformation directly but needs to basically forward that to the canvas API. It does so in the transformation setter which you circumvent by using the setFrom method. Do framebuffer.g2.transformation = backup instead (the setter is inlined and then uses setFrom internally so you don't pay a performance penalty for it).
