### ISSUE TITLE
Kha program crashes when assets are used [Windows target]. 

### ISSUE THREAD

**Issue by cozast** [Kode/Kha#1196]
When I target windows and assets are used in my game the compiled output outputs an: "unknow error", when I remove all assets from my game the game works correctly;

I tried on:
2 different PCs;
Haxe Toolkit v. 4.0.5 and 3.4.7;
Kha git and haxelib version;

**Comment by MoritzBrueckner** [comment]
I once got the same issue with a file of an unsupported file type in the asset directory. Maybe check if that's the case with your project?

Maybe there should be a better error message when that happens.

**Comment by RobDangerous** [comment]
Sorry but this does not look like a bug report for Kha but like a bug report for your game. Please learn how to use the Visual Studio debugger so you can see what's going on. When you continue to have problems, please create a minimal example and upload it somewhere so we can have a look.
Two remarks though: The installed version of Haxe is irrelevant because Kha uses an integrated version of Haxe and the haxelib version of Kha is completely outdated and not recommended for use, ever.
