### ISSUE TITLE
g2.drawImage() issue on android target

### ISSUE THREAD

**Issue by joydance** [Kode/Kha#1424]
**Describe the bug**
g2.drawImage() doesn't display any image when target android platform.
I've tried ios, html5, macosx, android-native, all works fine.

**Expected behavior**
Android can drawImage correctly.

**Screenshots**
![Screenshot_20220716-104217_Kha Test](https://user-images.githubusercontent.com/218745/179336311-07dec0ee-dcf3-4280-9083-a438ba1afcee.jpg)

**Comment by RobDangerous** [comment]
Currently asking in the Discord if anyone minds if I just remove the backend. Do you actually want to use it for something or was it just out of curiosity?

**Comment by joydance** [comment]
I think pure java code is cool and useful when imported as a lib/moudle to an existing android project.  One important thing is that it's also very suitable for debuging (hxcpp is hard). Although I haven't try much. I think different target language (not only hxcpp or js) is one of most important reason why choose among kha, open and heaps. :)

**Comment by RobDangerous** [comment]
Haxe-generated Java looks a lot like Haxe-generated C++, I don't think it's easier to debug. The problem with Android-Java is that it will always have bad performance, bad audio-support and outdated graphics-support due to restrictions in Android's Java-APIs which by now I think Google will never take care of - the text that's printed when you use the Android-target also warns about that and I would strongly advise against using it for any real project. The only nice thing is that it compiles relatively quickly.

**Comment by joydance** [comment]
What you list is very convincing pitch. I'll focus on android-native then. Thanks. :)
