### ISSUE TITLE
kha.Storage.defaultFile should be unique to the app on web

### ISSUE THREAD

**Issue by wighawag** [Kode/Kha#463]
As mentioned on IRC :
 
could defaultFile on html5 be something app specific as opposed to "default.kha" ? This way we could still use defaultFile on the web without mixing different game from the same domain

This way defaultFile would behave like it does on mobile : separated from other apps

We could use the project name ?

**Comment by romamik** [comment]
IMHO it should me something like 'window.location.href', not the project name. Because someone may want to put two distinct instances of same application on the same domain.

**Comment by wighawag** [comment]
Thanks romanik for your input.

In my opinion window.location.href is not a good option for the following reason :
- website that have different url for the same resources. 
- brittle : if the website change its url, every user lose its data

Could you explain a bit more of your use case for 2 game instances?

I imagine that in that case the user would like to get the same data (score, audio preferences..) shared between both. no ?

If not the developer can version the project name of the instances so they do not conflict. Alternatively it could use "Storage.namedFile"

I think using the project name solve the current issue better as it is independent of the website design

**Comment by romamik** [comment]
First of all we should speak not only about default file, but about any kha.StorageFile. 
Should it be shared between different instances of the same application or not?
Should it be shared between different applications?
After some thinking I do not know right answers for both questions. My previous answer was based on your opinion that file should be "separated from other apps" and on flash backend behavior.
Different kha backends have different behavior:
1. Flash - files are unique per SWF file URL
2. HTML5 - files are unique per domain, i.e. available to different applications and different instances of one application on the same domain
3. Windows - files are unique per application name
4. Android - files are unique per application instance (but you can't have more than one instance of one application...)

As for specifically web applications I think that if the data is valuable it should be stored on server, not locally, because it's too easy to loose local storage data, and should be bound to the user using some authentication mechanism. That solves both issues, but goes out of scope.

**Comment by wighawag** [comment]
Hi @romamik  thanks for mentioning platform differences

Could you point me to where you found that flash are unique per URL. I always thought it behaved similar to cookies as mentioned here : http://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118a9b90204-7c9a.html

As for the use of a server side, this is indeed out of scope and not the same thing. There is definitely some case where you want to store it locally only.

As for the solution I proposed for ```defaultFile``` I still think it is better than what we have now.

My main point was that while ```defaultFile``` for the other platform are separated from other app, in case of html5 (and I guess flash, (did not have a look there) the data is currently shared accross games. This is of course an issue for website that contains multiple different games. You basically cannot use ```defaultFile``` without having the saved data mixed among the multiple games

For namedFile, this is a bit different since the developer is in control. But the documentation should definitely mention the risk of collision of the same named file is used.
Actually a solution could involved prepending the application name

**Comment by RobDangerous** [comment]
"brittle : if the website change its url, every user lose its data" <- doesn't this happen anyway with cookies and/or local storage?

**Comment by romamik** [comment]
From http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/SharedObject.html#getLocal() :

>  To avoid name conflicts, Flash looks at the location of the SWF file creating the shared object. For example, if a SWF file at www.myCompany.com/apps/stockwatcher.swf creates a shared object named portfolio, that shared object does not conflict with another object named portfolio that was created by a SWF file at www.yourCompany.com/photoshoot.swf because the SWF files originate from different directories. 

So I was not exactly right, but anyway flash shared objects are more isolated than HTML5 local storage.

**Comment by wighawag** [comment]
@RobDangerous not if the domain is the same

**Comment by RobDangerous** [comment]
I add the titel (plus there's a temporary hack for backwards-compatibility which might also cause some trouble).
