### ISSUE TITLE
Decrypting password protected zip files

### ISSUE THREAD

**Issue by hsdk123** [Kode/Kha#475]
Hi, I was wondering if Kha might have some functionality to decode password protected zip files - just something small, but practical for locking assets for the game.

**Comment by RobDangerous** [comment]
There's no asset packing functionality currently if your looking for that. For plain zip support you can use Haxe's own zip functionality or some other lib, don't know about password support though.
Not sure what your exact requirements are but If it's really just about protecting assets, that kinda happens automatically for images when you compile to a native target because Kha uses its own lz4 compressed image format and will soon also do that for other types of assets - which incidentally is probably better protection than a zip with a password.
