### ISSUE TITLE
html5 performance of gl.getError

### ISSUE THREAD

**Issue by romamik** [Kode/Kha#674]
Not so long ago (in commit f84b32f92d87dfe1cd68bf7da4b5c6500b146ca9) `g4.end() ` function where modified so that it now calls `gl.getError()`.

It looks like that this is expensive performance-wise. At least in chrome. I've tested on different machines and it takes from at least 10ms on modern i5 to hundreds ms on lower end computers.

Maybe we can make this optional? 

This is the code I've used:
```
package;

import haxe.Timer;
import kha.Color;
import kha.Framebuffer;
import kha.System;

class Main {
	
	public static function main() {
		System.init({title: "Project", width: 1024, height: 768}, function () {
			new Main();
		});
	}
	
	public function new() {
		
		System.notifyOnRender(render);
	}

	function render(framebuffer: Framebuffer): Void {
		
		var g = framebuffer.g2;
		
		g.begin();
		for (i in 0...1000) {
			g.color = Color.fromFloats(Math.random(), Math.random(), Math.random(), 0.5);
			g.fillRect(100+i, 100+i, framebuffer.width - 200, framebuffer.height - 200);
		}
		
		Timer.measure(g.end);
	}
}
```

**Comment by RobDangerous** [comment]
Definitely, will make it debug only.

**Comment by OvermindDL1** [comment]
For note, gl_getError is expensive regardless of the system, it forces a flush of the entire OpenGL pipeline at that point, preventing parallel GPU work across it.  It is usually good to run once per frame at the start of the frame (since the previous frames work should be done by then) or if you detect an error condition in some return of the few gl calls that tell you there is an error.

**Comment by RobDangerous** [comment]
It's worse than that, I've seen it crash drivers when called too often. Anyways, it's debug only now.
