### ISSUE TITLE
Chrome 66 now blocks automatic playing of web-audio

### ISSUE THREAD

**Issue by OlegAntipov** [Kode/Kha#816]
So kha.audio2 does not work properly on html5 target now. It is necessary to do something with this...

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by RobDangerous** [comment]
Oh boy, that Media Engagement nonsense makes this the worst thing ever to debug.

**Comment by RobDangerous** [comment]
Aha, command line switches at least.

**Comment by RobDangerous** [comment]
Partially resolved. Let's see if anyone has any cool hints regarding https://twitter.com/robdangerous/status/994972723955879936

**Comment by OlegAntipov** [comment]
It's not a problem to make a "Play" button in the preloader to initiate a click, but when I call audio2.play for some reason the sound is not played even after clicking on the canvas... Unlike Audio2.stream starts playing after any click on the document :-/

**Comment by RobDangerous** [comment]
Are you sure about that? Because for me it's the exact opposite.

**Comment by RobDangerous** [comment]
Oh, also, Audio2.play does not exist, that's just an error in the documentation aka the Empty backend. We are talking about Audio1, right?

**Comment by OlegAntipov** [comment]
Yes, sorry I mean kha.audio1.Audio. And play sound like "Audio.play(...)"

I launch html5 like this: 
node C:/Development/Kha/make html5  
start chrome.exe http://localhost:8080
node C:/Development/Kha/make --server

This is my actions:
1) start html5 in chrome
2) Audio.stream(...) and Audio.play(...) didn't work.
3) Got in console "Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD"
4) click on canvas
5) Audio.stream(...) worked, but not Audio.play(...).
6) no errors in console

**Comment by OlegAntipov** [comment]
I noticed that if you quickly click on the page during the loading, sometimes the Audio.play(...) and Audio.stream(...) are played normally but sometimes not.

**Comment by RobDangerous** [comment]
Is your Kha up to date? Can you see the resume calls (https://github.com/Kode/Kha/blob/master/Backends/HTML5/kha/SystemImpl.hx#L587) happening?

**Comment by OlegAntipov** [comment]
oh, did not notice the update, one moment ...

**Comment by RobDangerous** [comment]
What are you doing, stream isn't fixed yet, streams which were started before a first click still stay silent.

**Comment by OlegAntipov** [comment]
ok, I forgot about it.

**Comment by RblSb** [comment]
I think we'll have to put up with the new limitation in browsers and start all the audio stuff with the buttons for the first click/etc. Even if there is a hack, it will be quickly studied by spam sites and just as quickly closed.
https://www.dailydot.com/debug/chrome-autoplay-block-games/

**Comment by RobDangerous** [comment]
Well, no, we don't, because I haz a plan.

**Comment by koonsolo** [comment]
I came across this same issue when adding music to my RPG Playground project.

What happens in Chrome is that when your page starts and you call _Audio1.stream()_, but you don't do any interactions, the _element.play()_ in AEAudioChannel.play() throws a DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD. But remark that this is thrown through a promise!!!

When you do interact with the page first, this exception is not thrown.

The problem is that I'm unable to catch this exception, since it's thrown in a promise (https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play), and the Kha code doesn't handle this.

As I see it, there are 3 ways on how to solve this. The first one doesn't require any change in Kha.

1. User program doesn't play any music until the canvas becomes active. This might be a good idea anyway, and also pause the music (and gameplay) when it loses focus. This doesn't require any change in Kha. You can still decide to do this is all browsers, or only in Chrome.

2. Kha catches the exception in the promise, and notifies the user program. This way the user can decide for themselves how to handle this exception

3. Kha catches the exception, and handles it internally. Maybe start streaming when the canvas does become active?

Anyway, I think I'm going for option 1 right now, since I want to put a new version out for my users :). 

But maybe it's a good idea for Kha to at least try to push this exception onto the user, since right now it's basically brushed under the carpet.

**Comment by RobDangerous** [comment]
Nah, I will make Audio.stream behave the same way Audio.play works in Chrome and mobile browsers (tracking internally what would happen if the sound would be on and jumping in at that point at first contact with a finger/cursor click). I started on that and think I'll finish it next week.

**Comment by koonsolo** [comment]
So I don't have to do anything and just wait until next week? That solution works for me! ;)

**Comment by RobDangerous** [comment]
Aye

**Comment by koonsolo** [comment]
@RobDangerous, any news on this? If you need any help just let me know.

**Comment by RobDangerous** [comment]
Sorry, have to finish some work which turned out more complicated than I thought. This one here is first on my todo list after that, hopefully next week.

**Comment by RobDangerous** [comment]
I'm still busy with "crazy project"(tm) but it's finally getting somewhere and I'm slowly getting back to doing more Kha things. And this one was first on my todo list, so...
