### ISSUE TITLE
Documentation outdated or?

### ISSUE THREAD

**Issue by Liburn** [Kode/Kha#888]
I'm newbie trying Kode Studio for the first time. I'm following https://github.com/Kode/Kha/wiki/Getting-Started, but there is no "Compile Kha Project" command available for me in Kode Studio. I'm using v. 18.9.0.   Actual version is 18.9.2, in commits I don't see anything related to my problem.

**Comment by RobDangerous** [comment]
Yes, that changed a little, thanks for reporting it. I updated the wiki page.

**Comment by Liburn** [comment]
Thanks, but now I'm getting

![image](https://user-images.githubusercontent.com/3929966/46146505-3ca81780-c263-11e8-85b9-63109e7c510f.png)

followed by

![image](https://user-images.githubusercontent.com/3929966/46146571-64977b00-c263-11e8-8a34-609f27a05066.png)

**Comment by RobDangerous** [comment]
ok, the first error is actually trying to tell you that it can't find a compiled application (but fails to open the dialog for that - that's an actual bug, sorry). Are you really on 18.9.2? What does "I'm using v. 18.9.0. Actual version is 18.9.2" mean? 18.9.0 failed to build things because I forgot to include some files but I can not reproduce that behavior in 18.9.2. What's the output of the terminal panel at the bottom?

**Comment by Liburn** [comment]
It means, I downloaded v. 18,9.0 several days ago, now I'm trying it. I skipped v. 18.9.2 because I couldn't find in commits anything related to my first reported problem. Should I download v. 18.9.2 instead and try it?

**Comment by RobDangerous** [comment]
Ah! Yes, please.

**Comment by Liburn** [comment]
OK, v. 18.9.2 is working fine. Now I'm trying Build For Windows command, build is there, but no executable. How do I build executable?

**Comment by RobDangerous** [comment]
There should now be a .sln file in build/windows-build - open that in Visual Studio to build debug or release builds.
