### ISSUE TITLE
--ffmpeg required even though it can be found in PATH

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#976]
```text
$ node Kha/make html5
Using Kha from /Users/Joncom/Desktop/video_example_kha/Kha
Creating Kha project.
Exporting asset 1 of 1 (movie.mp4).
Video file /Users/Joncom/Desktop/video_example_kha/Assets/movie.mp4 could not be exported, you have to specify a path to ffmpeg.
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
```

Specifically, "**you have to specify a path to ffmpeg.**"

Seems silly because:

```text
$ which ffmpeg
/usr/local/bin/ffmpeg
```

Any particular reason why it would be better to require an extra argument like this? Why not just make the argument optional, in the (unlikely?) case you want to override the default?

**Comment by RobDangerous** [comment]
Sorry, not happening, two reasons:
* Kha in general avoids calling non-included programs just like that. It's an obtrusive thing to do IMHO (and I know I'm pretty much alone with that opinion) and therefore I try to make all of that explicit (via --compile and --ffmpeg). Being explicit with all of that also helps with isolating bugs.
* Using ffmpeg is a potential legal problem because of the patents situation. That's also the reason I do not include it directly (which I do for ogg and mp3 encoders). Using ffmpeg is therefore not a decision to make lightly and certainly not a decision I want to make on behalf of anybody else by searching his computer for some executable.
